version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - echo Build started on `date`
      - echo IMAGE_TAG=$IMAGE_TAG
  build:
    commands:
      - echo Building the Spring Boot application...
      - mvn clean package -DskipTests
      - echo Building the Docker image...
      - docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
      - docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REPOSITORY:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $ECR_REPOSITORY:$IMAGE_TAG
      - docker push $ECR_REPOSITORY:latest
      - echo Creating imagedefinitions.json file for ECS...
      - echo '[{"name":"springboot-container","imageUri":"'$ECR_REPOSITORY:$IMAGE_TAG'"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
