version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init
  build:
    commands:
      - echo "Applying Terraform..."
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo "Terraform Deployment Completed"
artifacts:
  files:
    - "**/*"
